---
apiVersion: v1
kind: Service
metadata:
  name: custrewardmgtsys-v3-api
spec:
  type: ClusterIP
  selector:
    app: custrewardmgtsys-v3-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
